# Reader defined commands
RESET_READER = b"\x21"
GET_FIRMWARE_VERSION = b"\x22"

SET_RADIO_POWER = b"\x25"
GET_RADIO_POWER = b"\x26"
SET_RADIO_FREQUENCY = b"\x27"
GET_RADIO_FREQUENCY = b"\x28"

GEN2_SECURED_READ = b"\x88"
GEN2_SECURED_WRITE = b"\x89"
GEN2_SECURED_LOCK = b"\x8A"

# RF frequency settings
RADIO_FREQUENCY_CHINA = 0
RADIO_FREQUENCY_USA = 1
RADIO_FREQUENCY_EUROPE = 2
RADIO_FREQUENCY_CUSTOM = 3

# Memory Bank IDs
RESERVED = 0
EPC = 1
TID = 2
USER = 3

# Lock levels
UNLOCK = 0
UNLOCK_FOREVER = 1
SECURE_LOCK = 2
LOCK_FOREVER = 3
